---
title: "Pitcher Numbers"
author: "Ant"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---

```{r setup, include = FALSE, echo = FALSE}
library(tidyverse)
library(lubridate)
library(gt)
library(paletteer)
library(plotly)
library(flexdashboard)

#Working directory for .RMD
knitr::opts_knit$set(echo = TRUE,
                     root.dir = rprojroot::find_rstudio_root_file())

#Controlling figure output in markdown
knitr::opts_chunk$set(
#  fig.height =   
  fig.width = 6,
#  fig.asp = .5,
  out.width = "90%",
#  out.height = 
 fig.align  = "center",
  cache = FALSE,
  eval  = TRUE,
  echo  = TRUE,
  warning = FALSE
)

#My Colours (from viridis)
my_purple <- "#440154FF"
my_yellow <- "#FDE725FF"

#Set Theme for ggplot2
theme_set(theme_bw() + theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom"))

#Set Scientific notation output and decimal places for knitr
options(scipen = 999)
options(digits = 4)
options(dplyr.summarise.inform = FALSE)
```


```{r data_read, include = FALSE}
bball <- read_rds("./data/baseball.rds")
(b = bball %>%
  mutate(Date = as.character(Date), Date = ymd(Date), Day = factor(Day, ordered = TRUE), Day = ordered(Day, levels = c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")), Attendance = as.numeric(Attendance), DayNight = factor(DayNight)))
```

### Number of Pitchers over time

```{r, echo=FALSE}
b %>%
  mutate(numpitch = VisitNumPitchers + HomeNumPitchers) %>%
  mutate(text_label = str_c(year, "\n Avg. # Pitchers", numpitch)) %>%
  filter(year >= 1900) %>%
  group_by(year) %>%
  summarize(avg_pitch = mean(numpitch, na.rm = T), text_label = text_label) %>%
  ggplot(aes(x = as.numeric(year), y = avg_pitch, text = text_label, color = avg_pitch)) +
  geom_point() +
  scale_x_continuous(breaks = seq(1900, 2021, 10)) +
  labs(x = "Season", y = "Average Pitchers Used Per Game", title = "Average Pitchers Used Per Game by Season") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 0))
```

### Number of pitchers in 2019

```{r, include=FALSE}
season_2019 <- b %>%
  mutate(numpitch = VisitNumPitchers + HomeNumPitchers) %>%
  mutate(text_label = str_c("Date: ", Date, "\n# of Pitchers: ", numpitch)) %>%
  filter(year %in% 2019) %>%
  ggplot(aes(x = Date, y = numpitch)) +
  geom_point(aes(text = text_label), position = position_jitter()) +
  stat_smooth() +
  scale_x_date(date_breaks = "1 month", date_labels = "%B") +
  labs(y = "# of Pitchers Used", title = "Number of Pitchers Used Over 2019 Season")
```



```{r, include=FALSE}
ggplotly1 <- ggplotly(season_2019)
```


```{r, echo=FALSE}
tot_pitch <- b %>% mutate(numpitch = VisitNumPitchers + HomeNumPitchers) %>% filter(year %in% 2019)
text_label <- str_c("Date: ", tot_pitch$Date, "\n# of Pitchers: ", tot_pitch$numpitch)
ggplotly1 %>%
  style(text = text_label, traces = 1) %>%
  style(text = text_label, traces = 2)
```
