---
title: "Did the number of pitchers used in a game increase over time (both between seasons and within seasons)?"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---

```{r setup, include = FALSE, echo = FALSE}
library(tidyverse)
library(lubridate)
library(gt)
library(paletteer)
library(plotly)
library(flexdashboard)

#Working directory for .RMD
knitr::opts_knit$set(echo = TRUE,
                     root.dir = rprojroot::find_rstudio_root_file())

#Controlling figure output in markdown
knitr::opts_chunk$set(
#  fig.height =   
  fig.width = 6,
#  fig.asp = .5,
  out.width = "90%",
#  out.height = 
 fig.align  = "center",
  cache = FALSE,
  eval  = TRUE,
  echo  = TRUE,
  warning = FALSE
)

#My Colours (from viridis)
my_purple <- "#440154FF"
my_yellow <- "#FDE725FF"

#Set Theme for ggplot2
theme_set(theme_bw() + theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom"))

#Set Scientific notation output and decimal places for knitr
options(scipen = 999)
options(digits = 4)
options(dplyr.summarise.inform = FALSE)
```


```{r data_read, include = FALSE}
bball <- read_rds("./data/baseball.rds")
(b = bball %>%
  mutate(Date = as.character(Date), Date = ymd(Date), Day = factor(Day, ordered = TRUE), Day = ordered(Day, levels = c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")), Attendance = as.numeric(Attendance), DayNight = factor(DayNight)))
```

### Number of Pitchers over Every Season from 1900-2021

```{r, echo=FALSE, fig.width=12}
b %>%
  mutate(numpitch = VisitNumPitchers + HomeNumPitchers) %>%
  mutate(text_label = str_c(year, "\n Avg. # Pitchers", numpitch)) %>%
  filter(year >= 1900) %>%
  group_by(year) %>%
  summarize(avg_pitch = mean(numpitch, na.rm = T), text_label = text_label) %>%
  ggplot(aes(x = as.numeric(year), y = avg_pitch, text = text_label, color = avg_pitch)) +
  geom_point() +
  geom_segment(aes(x = as.numeric(year), xend = as.numeric(year), y = 0, yend = avg_pitch)) +
  scale_x_continuous(breaks = seq(1900, 2021, 10)) +
  labs(x = "Season", y = "Average Pitchers Used Per Game", title = "Average Pitchers Used Per Game by Season", color = "Average # of \nPitchers per Game") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 0))
```

### Number of Pitchers over 2019

```{r, include=FALSE}
avg_2019 <- b %>%
  mutate(numpitch = VisitNumPitchers + HomeNumPitchers) %>%
  filter(year %in% 2019) %>%
  group_by(Date) %>%
  summarize(pitch = sum(numpitch)/n()) %>%
  ggplot(aes(x = Date, y = pitch)) +
  geom_point() +
  geom_smooth() +
  geom_vline(aes(xintercept = as.numeric(ymd("2019-10-1"))), color = "blue") +
  scale_x_date(date_breaks = "1 month", date_labels = "%B") +
  annotate("text", label = "Playoffs Start", x = ymd("2019-10-12"), y = 14.5, color = "blue") +
  labs(y = "Average # of Pitchers Used", title = "Average Number of Pitchers Used Over 2019 Season")
```

```{r, include=FALSE}
ggplotly2019 <- ggplotly(avg_2019)
```


```{r, echo=FALSE}
tot_pitch <- b %>% mutate(numpitch = VisitNumPitchers + HomeNumPitchers) %>% filter(year %in% 2019) %>%  group_by(Date) %>% summarize(pitch = sum(numpitch)/n())
text_label <- str_c("Date: ", month(tot_pitch$Date, label = T), " ", day(tot_pitch$Date), "\nAvg. # of Pitchers: ", round(tot_pitch$pitch, digits = 3))
ggplotly2019 %>%
  style(text = text_label, traces = 1) %>%
  style(text = text_label, traces = c(2,3,4)) 
```


### Numbers of Pitchers used per Year in the 30 Team Era Years

```{r, include=FALSE}
thirty_team <- b %>%
  mutate(numpitch = VisitNumPitchers + HomeNumPitchers) %>%
  filter(year %in% 1998:2021) %>%
  group_by(year) %>%
  summarize(pitch_year = sum(numpitch)) %>%
  mutate(text_label = str_c("Year: ", year, "\nPitchers Used: ", pitch_year)) %>%
  ggplot(aes(x = year, y = pitch_year, fill = pitch_year, text = text_label)) +
  geom_col() +
  labs(x = "Season", y = "Pitchers per Year", title = "Number of Pitchers used per Year in 30 Team Era", fill = "Total Number of Pitchers") +
  scale_y_continuous(labels = scales::comma) +
  scale_fill_continuous(labels = scales::comma)
```

```{r, echo=FALSE}
ggplotly(thirty_team, tooltip = "text")
```
